Feat add Profile Page without main functionality
ReCoded-Org/capstone-istanbul-no_barriers pull request #82
Opened 2020-11-15 11:55 UTC by fadime-ozdemir

Create profile page file structure and components:

1. Personal Information displays main info about the user.
2. Personal Blog posts displays his/her recent 3 blogs.
3. Edit Profile is a modal which allows users to change their name, email, phone number, profile picture and bio.

Right now the states in Personal Information and Personal Blog posts are hard coded. In another pr I'll add firebase and wordpress functionalities.

Profile- Personal Information
![React App - Google Chrome 14_11_2020 18_51_58](https://user-images.githubusercontent.com/12509733/99184229-65950a80-2752-11eb-9032-b4ec09ea4c8b.png)

Profile- Personal Blog posts
![React App - Google Chrome 14_11_2020 18_52_21](https://user-images.githubusercontent.com/12509733/99184243-7ba2cb00-2752-11eb-9e93-d1cf56795868.png)

Edit profile button on hover and click
![React App - Google Chrome 14_11_2020 18_52_04](https://user-images.githubusercontent.com/12509733/99184247-80677f00-2752-11eb-958a-d100afb48501.png)

Write blog post button on hover and click
![React App - Google Chrome 14_11_2020 18_52_24](https://user-images.githubusercontent.com/12509733/99184256-91b08b80-2752-11eb-8c26-7fabd0093eae.png)

Blog Post on hover and click
![React App - Google Chrome 14_11_2020 18_52_29](https://user-images.githubusercontent.com/12509733/99184261-9ecd7a80-2752-11eb-8189-71e2fdb26e88.png)

2020-11-16 22:40 UTC, khaldoon9kh requested changes
I like the work you did on the page. However, linking this page with a profile now will make our life hell!
Because, we need to start setting up redux for each part of this profile; photo, bio, filter post by author, write new posts, save favorites NGO, and send them to firesbase.

Especially with the limited amount of time.
I think we need to discuss this further.

2020-11-16 22:40 UTC, khaldoon9kh commented on src/components/PersonalBlogPosts/index.css
> +}
it's better to leave the button visible rather than transparent.
we can make it to get darker as another option.

2020-11-17 06:18 UTC, fadime-ozdemir commented
> I like the work you did on the page. However, linking this page with a profile now will make our life hell!
> Because, we need to start setting up redux for each part of this profile; photo, bio, filter post by author, write new posts, save favorites NGO, and send them to firesbase.
> 
> Especially with the limited amount of time.
> I think we need to discuss this further.

I think here we need to send only the user which has the id, the name and the mail, the other things will be inserted by the user manually so at the beginning it is empty.

2020-11-17 07:23 UTC, fadime-ozdemir commented
PTAL

2020-11-17 11:06 UTC, halitbatur approved these changes
few changes

2020-11-17 11:06 UTC, halitbatur commented on src/components/EditProfile/index.jsx
> +  const [input, setInput] = useState(info);
between line 7 and 8 new line

2020-11-17 11:06 UTC, halitbatur commented on src/components/EditProfile/index.jsx
> +  const handleSubmit = () => {
newline here between line 9 and 10

2020-11-17 11:06 UTC, halitbatur commented on src/components/EditProfile/index.jsx
> +  const handleInputChange = (e, idInput) =>
lets change the parameter 'e' since most of the time it refers to an event

2020-11-17 14:30 UTC, fadime-ozdemir commented
PTAL

2020-11-18 20:12 UTC, halitbatur approved these changes

2020-11-18 20:12 UTC, halitbatur commented on src/components/EditProfile/index.jsx
> +  const handleInputChange = (event, idInput) =>
this function should hace curly brackets

2020-11-18 20:13 UTC, halitbatur commented
@fadime-ozdemir resolve conflicts
 and its ready to be merged

2020-11-19 06:54 UTC, fadime-ozdemir commented
PTAL

2020-11-19 18:53 UTC, halitbatur commented
@fadime-ozdemir there's more conflicts xD

2020-11-20 08:18 UTC, fadime-ozdemir commented
> @fadime-ozdemir there's more conflicts xD

X'D I didn't notice it

2020-11-20 08:19 UTC, fadime-ozdemir commented
PTAL

2020-11-20 11:00 UTC, halitbatur approved these changes

2020-11-20 11:02 UTC, khaldoon9kh commented
> > I like the work you did on the page. However, linking this page with a profile now will make our life hell!
> > Because, we need to start setting up redux for each part of this profile; photo, bio, filter post by author, write new posts, save favorites NGO, and send them to firesbase.
> > Especially with the limited amount of time.
> > I think we need to discuss this further.
> 
> @khaldoon9kh I think here we need to send only the user which has the id, the name and the mail, the other things will be inserted by the user manually so at the beginning it is empty.

Oh you are right then!

LGTM

2020-11-20 11:06 UTC, khaldoon9kh approved these changes
LGTM,

Just make sure you link it to the NavBar as well.

2020-11-20 11:06 UTC, merged